# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 779)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textFullAddress = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.textFullAddress.setReadOnly(True)
        self.textFullAddress.setObjectName("textFullAddress")
        self.gridLayout.addWidget(self.textFullAddress, 4, 0, 1, 2)
        self.checkDarkTheme = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkDarkTheme.setObjectName("checkDarkTheme")
        self.gridLayout.addWidget(self.checkDarkTheme, 0, 3, 1, 1)
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 4, 2, 1, 2)
        self.map_canvas = QtWidgets.QLabel(parent=self.centralwidget)
        self.map_canvas.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.map_canvas.setStyleSheet("background: gray;")
        self.map_canvas.setText("")
        self.map_canvas.setScaledContents(True)
        self.map_canvas.setObjectName("map_canvas")
        self.gridLayout.addWidget(self.map_canvas, 1, 0, 1, 4)
        self.btnAddress = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddress.setObjectName("btnAddress")
        self.gridLayout.addWidget(self.btnAddress, 2, 3, 1, 1)
        self.isPostalCode = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.isPostalCode.setObjectName("isPostalCode")
        self.gridLayout.addWidget(self.isPostalCode, 2, 2, 1, 1)
        self.inputAddress = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputAddress.setObjectName("inputAddress")
        self.gridLayout.addWidget(self.inputAddress, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Большая задача по Maps API"))
        self.checkDarkTheme.setText(_translate("MainWindow", "темная тема"))
        self.btnClear.setText(_translate("MainWindow", "сброс поискового результата"))
        self.btnAddress.setText(_translate("MainWindow", "найти"))
        self.isPostalCode.setText(_translate("MainWindow", "почтовый индекс"))
        self.inputAddress.setPlaceholderText(_translate("MainWindow", "введите адрес..."))
